<?php

/**
 * Textformatter Normalize UTF8
 *
 * See README.md for usage instructions.
 *
 * ProcessWire 2.x
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 *
 * @author Tabea David <info@justonestep.de>
 * @version 0.0.1
 * @copyright Copyright (c) 2015 KF Interactive, www.kf-interactive.com, <info@kf-interactive.com>
 * @see https://github.com/justonestep/processwire-textformatter-normalizeutf8
 * @see http://www.processwire.com
 */

/**
 * Class TextformatterNormalizeUtf8
 */
class TextformatterNormalizeUtf8 extends Textformatter {

  /**
   * Retrieves module meta data
   * Implementation of the Module interface
   *
   * @return array
   * @see http://processwire.com/apigen/class-Module.html
   */
  public static function getModuleInfo() {
    return array(
      'title' => 'Textfomatter Normalize UTF8',
      'summary' => 'Textformatter Normalize UTF8 uses a lightweight PHP class for UTF8 normalization.',
      'version' => 1,
      'href' => 'https://github.com/justonestep/processwire-textformatterii-normalizeutf8'
    );
  }

  /**
   * format string
   *
   * @param string $str
   */
  public function format(&$str) {
    if (!class_exists('Normalizer')) {
      require(wire('config')->paths->TextformatterNormalizeUtf8 . 'vendor/autoload.php');
    }

    $str = Normalizer::normalize($str);
  }
}
